[package]
authors = ["Luke Roberts <lukeroberts.j@gmail.com>"]
edition = "2018"
name = "variantly"
version = "0.1.0"

[dependencies]
Inflector = "*"
proc-macro2 = "*"
quote = "*"
syn = {version = "*", features = ["full"]}
uuid = {version = "*", features = ["v4"]}

[lib]
proc-macro = true
